# Google Cloud Build configuration for AI Slop Detection Backend
# 
# This configuration builds and deploys the FastAPI backend for AI-generated 
# content detection to Google Cloud Run.
#
# Prerequisites:
# - Enable Cloud Build, Cloud Run, and Container Registry APIs
# - Set up Cloud SQL instance (PostgreSQL) for database
# - Generate Gemini API key
# - Grant Cloud Build service account access to Secret Manager (if using secrets)
#
# Usage:
# gcloud builds submit --config cloudbuild.yaml \
#   --substitutions _GEMINI_API_KEY="your-api-key",_DB_USER="appuser",_DB_PASSWORD="password",_DB_HOST="/cloudsql/PROJECT:REGION:INSTANCE"
#
# For development deployment:
# gcloud builds submit --config cloudbuild.yaml \
#   --substitutions _DEBUG="true",_MEMORY="4Gi",_CPU="2",_GEMINI_API_KEY="key",_DB_USER="user",_DB_PASSWORD="pass",_DB_HOST="host"
#
# Required substitution variables:
# - _GEMINI_API_KEY: Google Gemini API key for chat functionality
# - _DB_USER: Database username
# - _DB_PASSWORD: Database password
# - _DB_HOST: Database host (use /cloudsql/PROJECT:REGION:INSTANCE for Cloud SQL)

steps:
  # Pull cache image early (runs in parallel with credential setup)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
      docker pull gcr.io/$PROJECT_ID/ai-slop-backend:latest || echo "No cache image found, continuing without cache"
    id: 'pull-cache'
    waitFor: ['-']  # Start immediately

  # Build backend Docker image (waits for both cache and credentials)
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '--cache-from', 'gcr.io/$PROJECT_ID/ai-slop-backend:latest', '-t', 'gcr.io/$PROJECT_ID/ai-slop-backend:latest', './backend' ]
    id: 'build-backend'
    waitFor: ['pull-cache']  # Wait for cache pull

  # Push backend image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/ai-slop-backend:latest' ]
    id: 'push-backend'
    waitFor: [ 'build-backend' ]

  # Deploy backend to Cloud Run (waits for push to complete)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ai-slop-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ai-slop-backend:latest'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8000'
      - '--set-env-vars'
      - 'DEBUG=${_DEBUG},DEVICE=${_DEVICE},DEFAULT_MODEL=${_DEFAULT_MODEL},LOG_LEVEL=${_LOG_LEVEL},GEMINI_API_KEY=${_GEMINI_API_KEY},DB_NAME=${_DB_NAME},DB_USER=${_DB_USER},DB_PASSWORD=${_DB_PASSWORD},DB_HOST=${_DB_HOST},DB_PORT=${_DB_PORT}'
      - '--memory'
      - '$_MEMORY'
      - '--cpu'
      - '$_CPU'
      - '--max-instances'
      - '$_MAX_INSTANCES'
      - '--min-instances'
      - '$_MIN_INSTANCES'
      - '--timeout'
      - '$_TIMEOUT'
    id: 'deploy-backend'
    waitFor: [ 'push-backend' ]  # Wait for push to complete fully

  # Verify deployment completed successfully
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'services'
      - 'describe'
      - 'ai-slop-backend'
      - '--region'
      - '$_REGION'
      - '--format'
      - 'value(status.url)'
    id: 'verify-deployment'
    waitFor: [ 'deploy-backend' ]  # Wait for deployment to complete

# Set timeout for the entire build
timeout: 3600s

# Configure build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

# Substitution variables with defaults
substitutions:
  _REGION: 'us-central1'
  _DEBUG: 'false'
  _DEVICE: 'cpu'
  _DEFAULT_MODEL: 'slowfast_r50'
  _LOG_LEVEL: 'INFO'
  _MEMORY: '16Gi'
  _CPU: '4'
  _MAX_INSTANCES: '1'
  _MIN_INSTANCES: '0'
  _TIMEOUT: '1800s'
  # Required environment variables (must be provided during build)
  _GEMINI_API_KEY: ''   # Set via gcloud builds submit --substitutions
  # Database connection components
  _DB_NAME: 'ai_slop_extension'  # Database name
  _DB_USER: ''          # Database user (set via substitutions)
  _DB_PASSWORD: ''      # Database password (set via substitutions) 
  _DB_HOST: ''          # Database host (set via substitutions)
  _DB_PORT: '5432'      # Database port
