steps:
  # Build backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/slowfast-detection-backend:$COMMIT_SHA', '.']
    id: 'build-backend'

  # Push backend image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/slowfast-detection-backend:$COMMIT_SHA']
    id: 'push-backend'
    waitFor: ['build-backend']

  # Deploy backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'slowfast-detection-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/slowfast-detection-backend:$COMMIT_SHA'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'DEBUG=${_DEBUG},DEVICE=${_DEVICE},DEFAULT_MODEL=${_DEFAULT_MODEL},LOG_LEVEL=${_LOG_LEVEL}'
      - '--memory'
      - '$_MEMORY'
      - '--cpu'
      - '$_CPU'
      - '--max-instances'
      - '$_MAX_INSTANCES'
      - '--min-instances'
      - '$_MIN_INSTANCES'
      - '--timeout'
      - '$_TIMEOUT'
    id: 'deploy-backend'
    waitFor: ['push-backend']

# Set timeout for the entire build
timeout: 3600s

# Configure build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_MEDIUM

# Substitution variables with defaults
substitutions:
  _REGION: 'us-central1'
  _DEBUG: 'false'
  _DEVICE: 'cpu'
  _DEFAULT_MODEL: 'slowfast_r50'
  _LOG_LEVEL: 'INFO'
  _MEMORY: '4Gi'
  _CPU: '2'
  _MAX_INSTANCES: '1'
  _MIN_INSTANCES: '0'
  _TIMEOUT: '900s'