target-version = "py311"

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

line-length = 140
indent-width = 4

[format]
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Prefer double quotes over single quotes.
quote-style = "double"

# Use `\n` line endings for all files (Unix)
line-ending = "lf"

[lint]
# Enable isort
extend-select = ["I"]

[lint.isort]
# Sort imports taking into account case sensitivity
case-sensitive = true
