"""Update PostMedia to use Facebook media IDs

Revision ID: 2449353db8c6
Revises: 808dd3b24b74
Create Date: 2025-08-21 19:05:32.708088

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2449353db8c6"
down_revision: Union[str, Sequence[str], None] = "808dd3b24b74"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("post_media", "id", existing_type=sa.VARCHAR(length=36), type_=sa.String(length=64), existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("post_media", "id", existing_type=sa.String(length=64), type_=sa.VARCHAR(length=36), existing_nullable=False)
    # ### end Alembic commands ###
