"""Add text image video AI probability and confidence columns

Revision ID: f2b2f22157a3
Revises: d34aea40a291
Create Date: 2025-08-19 03:50:31.693663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2b2f22157a3'
down_revision: Union[str, Sequence[str], None] = 'd34aea40a291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('text_ai_probability', sa.Float(), nullable=True))
    op.add_column('post', sa.Column('text_confidence', sa.Float(), nullable=True))
    op.add_column('post', sa.Column('image_ai_probability', sa.Float(), nullable=True))
    op.add_column('post', sa.Column('image_confidence', sa.Float(), nullable=True))
    op.add_column('post', sa.Column('video_ai_probability', sa.Float(), nullable=True))
    op.add_column('post', sa.Column('video_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'video_confidence')
    op.drop_column('post', 'video_ai_probability')
    op.drop_column('post', 'image_confidence')
    op.drop_column('post', 'image_ai_probability')
    op.drop_column('post', 'text_confidence')
    op.drop_column('post', 'text_ai_probability')
    # ### end Alembic commands ###
